PREPROCESSING:
  DATASET: FaceForensics
  SPLIT: val
  COMPRESSION: c23
  ROOT: /home/alvaro/tests_alvaro/dataset/FaceForensics++/c23/
  # FAKETYPE: [Deepfakes, Face2Face, FaceSwap, NeuralTextures]
  FAKETYPE: [Original]
  IMAGE_SUFFIX: png
  DATA_TYPE: frames
  LABEL: [real]
  facial_lm_pretrained: pretrained/shape_predictor_81_face_landmarks.dat
  N_LANDMARKS: 81
  SAMPLING:
    ACTIVE: False
    NUMBERS: 8
  DEBUG: False
